global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'staff-labs'
    environment: 'local'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'staff-labs-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'staff-labs-api'
          service: 'api'
